theme: jekyll-theme-cayman

# Site settings
title: "3D Gaussian Splatting in Biomedical Imaging"
description: "A curated collection of research papers and resources exploring the applications of 3D Gaussian Splatting (3DGS) in medical imaging."
baseurl: "" # Leave empty if hosted on GitHub Pages at root
url: "https://sonainjameel.github.io/Guassian-Splatting-in-Biomedical/"  # Update with actual URL

# Navigation structure
navbar-links:
  Home: "index.md"
  Papers:
    - "Volumetric Imaging": "papers/volumetric_imaging.md"
    - "Surgical Scene Reconstruction": "papers/surgical_reconstruction.md"
    - "Medical Image Synthesis": "papers/image_synthesis.md"
    - "Challenges & Future Directions": "papers/challenges_future.md"
  Contribute: "contribute.md"
  About: "about.md"

# GitHub Repository Details
github:
  repository_url: "https://github.com/sonainjameel/Guassian-Splatting-in-Biomedical"

# Markdown settings
markdown: kramdown
