remote_theme: just-the-docs/just-the-docs

# Site settings
title: "3D Gaussian Splatting in Biomedical Imaging"
description: "A curated collection of research papers and resources exploring the applications of 3D Gaussian Splatting (3DGS) in medical imaging."
baseurl: "/Guassian-Splatting-in-Biomedical"
url: "https://sonainjameel.github.io/Guassian-Splatting-in-Biomedical/"

# Navigation structure
nav_order: 1

# Enable search
search_enabled: true

# Navigation links
nav:
  - title: "Home"
    url: "{{ site.baseurl }}/"
  - title: "Papers"
    children:
      - title: "Volumetric Imaging"
        url: "{{ site.baseurl }}/papers/volumetric_imaging"
      - title: "Surgical Scene Reconstruction"
        url: "{{ site.baseurl }}/papers/surgical_reconstruction"
      - title: "Medical Image Synthesis"
        url: "{{ site.baseurl }}/papers/image_synthesis"
      - title: "Challenges & Future Directions"
        url: "{{ site.baseurl }}/papers/challenges_future"
  - title: "Contribute"
    url: "{{ site.baseurl }}/contribute"
  - title: "About"
    url: "{{ site.baseurl }}/about"
  - title: "Team"
    url: "{{ site.baseurl }}/team"
  - title: "Publications"
    url: "{{ site.baseurl }}/publications"

# GitHub Repository Details
github:
  repository_url: "https://github.com/sonainjameel/Guassian-Splatting-in-Biomedical"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  footnote_backlink: "&#8617;"

# Footer links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sonainjameel/Guassian-Splatting-in-Biomedical"
